meeting_minutes_summary_task:
  description: >
    Summarize the meeting transcript into a summary with the following transcript:
    {transcript}

    Write the summary to a file called "summary.txt" in the "meeting_minutes" directory.  This is provided by the tool.

    Write the action items to a file called "action_items.txt" in the "meeting_minutes" directory.  This is provided by the tool.

    I would like you to return the action items from the meeting transcript in the following format:
    - Action item 1
    - Action item 2
    - ...

    I would also like you to analyze the sentiment of the meeting transcript and write it to a file called "sentiment.txt" in the "meeting_minutes" directory.  This is provided by the tool.

  expected_output: >
    A summary of the meeting transcript and a list of action items.
  agent: meeting_minutes_summarizer

meeting_minutes_writing_task:
  description: >
    Write the meeting minutes based on the summary, action items and sentiment.  This should give everything needed to know based on summary and action items.
    Put them into a nice markdown document.

    - Use the provided current date and time for the meeting date: {current_date}
    - Use the company name Hansons CleanAir for the company name
    - User Jasmine for the name of the organizer
    - Create a list of attendees from the transcript 
    - The location was at the office
    - Include a timestamp of when the minutes were generated at the bottom of the document
  expected_output: >
    A meeting minutes document with current date, time, and generation timestamp
  agent: meeting_minutes_writer