summary_transcriber_task:
  description: >
    Transcribe the meeting transcript into a summary with the following transcript:
    {transcript}

    Write the summary to a file called "summary.txt" in the "meeting_minutes" directory.  This is provided by the tool.

    I would like you to return the summary of the meeting transcript in the following format:
    - Summary of the meeting transcript
  expected_output: >
    A summary of the meeting transcript
  agent: summary_transcriber

action_items_extractor_task:
  description: >
    Extract the action items from the meeting transcript with the following transcript:
    {transcript}

    Write the action items to a file called "action_items.txt" in the "meeting_minutes" directory.  This is provided by the tool.

    I would like you to return the action items from the meeting transcript in the following format:
    - Action item 1
    - Action item 2
    - ...
  expected_output: >
    A list of action items from the meeting transcript
  agent: action_items_extractor

meeting_minutes_writer_task:
  description: >
    Write the meeting minutes based on the summary and action items.  Both the summary and action items are provided by the file reader tools.
    Make sure to take each one, read the files, and put them together into a cohesive document.
  expected_output: >
    A meeting minutes document
  agent: meeting_minutes_writer
